export const SET_SESSIONS = 'SET_SESSIONS'

export const SET_SESSIONS_HEAP = 'SET_SESSIONS_HEAP'

export const SET_CUSTOMINFO_HEAP = 'SET_CUSTOMINFO_HEAP'

export const SET_MSGS_HEAP = 'SET_MSGS_HEAP'

export const SET_SUMMARY_HEAP = 'SET_SUMMARY_HEAP'
